// @ts-nocheck
/* eslint-disable */
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Add a message to a chat session.
 * 
 * This adds a user message to the session. The assistant response should be
 * handled separately via streaming or the response generation flow.
 */
async addChatMessage(sessionId: string, message: ChatMessage) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_chat_message", { sessionId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Archive a chat session.
 */
async archiveChatSession(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("archive_chat_session", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Add a manual profile
 */
async authAddProfile(request: AddProfileRequest) : Promise<Result<ProfileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_add_profile", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Clear all profiles
 */
async authClear() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_clear") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Disable a profile
 */
async authDisableProfile(profileId: string, reason: string) : Promise<Result<ProfileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_disable_profile", { profileId, reason }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run credential discovery
 */
async authDiscover() : Promise<Result<DiscoverySummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_discover") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Enable a profile
 */
async authEnableProfile(profileId: string) : Promise<Result<ProfileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_enable_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Check if an API key exists for a provider (selects best available profile)
 */
async authGetApiKey(provider: AuthProvider) : Promise<Result<boolean | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_api_key", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get available profiles (enabled, not expired, not in cooldown)
 */
async authGetAvailableProfiles() : Promise<Result<AuthProfile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_available_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a specific profile by ID
 */
async authGetProfile(profileId: string) : Promise<Result<AuthProfile | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get profiles for a specific provider
 */
async authGetProfilesForProvider(provider: AuthProvider) : Promise<Result<AuthProfile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_profiles_for_provider", { provider }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get manager summary
 */
async authGetSummary() : Promise<Result<ManagerSummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_get_summary") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Initialize the auth manager (run discovery)
 */
async authInitialize() : Promise<Result<DiscoverySummary, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_initialize") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all profiles
 */
async authListProfiles() : Promise<Result<AuthProfile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_list_profiles") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a profile as failed
 */
async authMarkFailure(profileId: string) : Promise<Result<ProfileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_mark_failure", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Mark a profile as successfully used
 */
async authMarkSuccess(profileId: string) : Promise<Result<ProfileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_mark_success", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove a profile
 */
async authRemoveProfile(profileId: string) : Promise<Result<ProfileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_remove_profile", { profileId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a profile
 */
async authUpdateProfile(profileId: string, update: ProfileUpdate) : Promise<Result<ProfileResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auth_update_profile", { profileId, update }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel a running agent task
 */
async cancelBackgroundAgent(taskId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_background_agent", { taskId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel an active chat stream.
 */
async cancelChatStream(sessionId: string, messageId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_chat_stream", { sessionId, messageId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Convert a chat session into a background agent
 */
async convertSessionToBackgroundAgent(request: ConvertSessionToBackgroundAgentRequest) : Promise<Result<BackgroundAgent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("convert_session_to_background_agent", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new agent
 */
async createAgent(request: CreateAgentRequest) : Promise<Result<StoredAgent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_agent", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new chat session.
 * 
 * # Arguments
 * * `agent_id` - The agent to chat with
 * * `model` - The model to use for responses
 * * `name` - Optional custom name for the session
 * * `skill_id` - Optional skill context
 */
async createChatSession(agentId: string, model: string, name: string | null, skillId: string | null) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_chat_session", { agentId, model, name, skillId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new secret (fails if key already exists)
 */
async createSecret(request: CreateSecretRequest) : Promise<Result<SecretInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_secret", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Create a new skill
 */
async createSkill(skill: Skill) : Promise<Result<Skill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_skill", { skill }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete an agent by ID
 */
async deleteAgent(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete an agent task
 */
async deleteBackgroundAgent(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_background_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a chat session.
 */
async deleteChatSession(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_chat_session", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a secret by key
 */
async deleteSecret(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_secret", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Delete a skill by ID
 */
async deleteSkill(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_skill", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Execute the agent for a chat session and save the response.
 * 
 * This command:
 * 1. Loads the chat session
 * 2. Gets the last user message as input
 * 3. Executes the agent
 * 4. Saves the assistant response to the session
 * 5. Returns the updated session
 */
async executeChatSession(sessionId: string) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_chat_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Export a skill to JSON
 */
async exportSkill(id: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_skill", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get an agent by ID
 */
async getAgent(id: string) : Promise<Result<StoredAgent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get available AI models with metadata
 */
async getAvailableModels() : Promise<Result<ModelMetadataDTO[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_available_models") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get events for a specific task
 */
async getBackgroundAgentEvents(taskId: string, limit: number | null) : Promise<Result<TaskEvent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_background_agent_events", { taskId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Return the background-agent stream event name.
 * 
 * Frontend can subscribe to this event and receive daemon-backed
 * background-agent stream payloads.
 * 
 * # Usage
 * 
 * ```typescript
 * import { listen } from '@tauri-apps/api/event';
 * import type { TaskStreamEvent } from './types/generated';
 * 
 * // Subscribe to all task events
 * const unlisten = await listen<TaskStreamEvent>('background-agent:stream', (event) => {
 * console.log('Received event:', event.payload);
 * });
 * 
 * // Later, unsubscribe
 * unlisten();
 * ```
 */
async getBackgroundAgentStreamEventName() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_background_agent_stream_event_name") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a chat session by ID.
 */
async getChatSession(id: string) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_chat_session", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get the heartbeat event name for frontend subscription
 * 
 * The heartbeat events are now emitted inline by the BackgroundAgentRunner during
 * its poll cycle, so there's no separate heartbeat runner to manage.
 * 
 * # Usage
 * 
 * ```typescript
 * import { listen } from '@tauri-apps/api/event';
 * import type { HeartbeatEvent } from './types/generated';
 * 
 * const unlisten = await listen<HeartbeatEvent>('background-agent:heartbeat', (event) => {
 * console.log('Heartbeat:', event.payload);
 * });
 * ```
 */
async getHeartbeatEventName() : Promise<string> {
    return await TAURI_INVOKE("get_heartbeat_event_name");
},
/**
 * Get the session change event name and start the event bridge.
 * 
 * Frontend should call this once at startup to begin receiving session change
 * events from the daemon (e.g. when Telegram adds a message).
 * 
 * # Usage
 * 
 * ```typescript
 * import { listen, invoke } from '@tauri-apps/api';
 * 
 * const eventName = await invoke<string>('get_session_change_event_name');
 * const unlisten = await listen<ChatSessionEvent>(eventName, (event) => {
 * // Refresh session list or specific session
 * });
 * ```
 */
async getSessionChangeEventName() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_session_change_event_name") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Get a skill by ID
 */
async getSkill(id: string) : Promise<Result<Skill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_skill", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all agents
 */
async listAgents() : Promise<Result<StoredAgent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all agent tasks
 */
async listBackgroundAgents() : Promise<Result<BackgroundAgent[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_background_agents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List chat session summaries.
 * 
 * More efficient than list_chat_sessions when full message history isn't needed.
 */
async listChatSessionSummaries() : Promise<Result<ChatSessionSummary[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_session_summaries") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all chat sessions.
 * 
 * Returns sessions sorted by updated_at descending (most recent first).
 */
async listChatSessions() : Promise<Result<ChatSession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_sessions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List chat sessions for a specific agent.
 */
async listChatSessionsByAgent(agentId: string) : Promise<Result<ChatSession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_sessions_by_agent", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List chat sessions for a specific skill.
 */
async listChatSessionsBySkill(skillId: string) : Promise<Result<ChatSession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_chat_sessions_by_skill", { skillId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List chunks for a specific session.
 */
async listMemoryChunksForSession(sessionId: string) : Promise<Result<MemoryChunk[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_memory_chunks_for_session", { sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List memory chunks by tag.
 */
async listMemoryChunksByTag(tag: string, limit: number | null) : Promise<Result<MemoryListResponse<MemoryChunk>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_memory_chunks_by_tag", { tag, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all memory sessions for an agent.
 */
async listMemorySessions(agentId: string) : Promise<Result<MemorySession[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_memory_sessions", { agentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all secrets (without values)
 */
async listSecrets() : Promise<Result<SecretInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_secrets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List all skills
 */
async listSkills() : Promise<Result<Skill[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_skills") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * List persisted tool traces for a chat session turn.
 */
async listToolTraces(sessionId: string, turnId: string | null, limit: number | null) : Promise<Result<ToolTrace[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_tool_traces", { sessionId, turnId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Pause an agent task
 */
async pauseBackgroundAgent(id: string) : Promise<Result<BackgroundAgent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("pause_background_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Read a media file from `~/.restflow/media/` and return its contents as base64.
 * Path must be under the media directory for security.
 */
async readMediaFile(filePath: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_media_file", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rebuild an externally managed chat session (Telegram/Discord/Slack).
 * 
 * This resets conversation history while preserving channel binding.
 */
async rebuildExternalChatSession(id: string) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rebuild_external_chat_session", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Rename a chat session.
 */
async renameChatSession(id: string, name: string) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_chat_session", { id, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Resume a paused agent task
 */
async resumeBackgroundAgent(id: string) : Promise<Result<BackgroundAgent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resume_background_agent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Run an agent task immediately.
 * 
 * This command currently triggers immediate execution via daemon IPC.
 * It keeps returning an event channel for API compatibility, but does not
 * guarantee full per-step stream delivery yet.
 * 
 * # Arguments
 * 
 * * `id` - The ID of the agent task to run
 * 
 * # Returns
 * 
 * Returns a `StreamingBackgroundAgentResponse` with the task ID and event channel name.
 * 
 * # Example (Frontend)
 * 
 * ```typescript
 * import { invoke } from '@tauri-apps/api/core';
 * import { listen } from '@tauri-apps/api/event';
 * 
 * // Start listening before invoking
 * const unlisten = await listen<TaskStreamEvent>('background-agent:stream', (event) => {
 * if (event.payload.task_id === taskId) {
 * switch (event.payload.kind.type) {
 * case 'started':
 * console.log('Task started:', event.payload.kind.task_name);
 * break;
 * case 'output':
 * console.log('Output:', event.payload.kind.text);
 * break;
 * case 'completed':
 * console.log('Done:', event.payload.kind.result);
 * break;
 * }
 * }
 * });
 * 
 * // Trigger task execution
 * const response = await invoke('run_background_agent_streaming', { id: 'task-123' });
 * console.log('Started task:', response.task_id);
 * ```
 */
async runBackgroundAgentStreaming(id: string) : Promise<Result<StreamingBackgroundAgentResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_background_agent_streaming", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Save audio as a file for AI to process with transcribe tool.
 * If `session_id` is provided, saves directly to `~/.restflow/media/{session_id}/`.
 * Otherwise saves to `~/.restflow/media/` (will be relocated by ChatDispatcher later).
 */
async saveVoiceMessage(audioBase64: string, sessionId: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_voice_message", { audioBase64, sessionId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a chat message and get a response.
 * 
 * This is a convenience command that:
 * 1. Adds the user message to the session
 * 2. Triggers response generation
 * 3. Adds the assistant response
 * 4. Returns the updated session
 * 
 * For streaming responses, use add_chat_message + response events instead.
 */
async sendChatMessage(sessionId: string, content: string) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat_message", { sessionId, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a chat message with streaming response.
 * 
 * This command:
 * 1. Adds the user message to the session
 * 2. Generates a message ID for the response
 * 3. Spawns a background task to execute the agent and stream events
 * 4. Returns the message ID immediately
 * 
 * The frontend should listen to 'chat:stream' events to receive updates.
 */
async sendChatMessageStream(sessionId: string, message: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_chat_message_stream", { sessionId, message }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a PCM16 audio chunk to an active live transcription session.
 */
async sendLiveAudioChunk(transcribeId: string, audioBase64: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_live_audio_chunk", { transcribeId, audioBase64 }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start a live transcription session using the OpenAI Realtime WebSocket API.
 * Returns a transcribe_id; text deltas arrive via Tauri `voice:transcribe-stream` events.
 */
async startLiveTranscription(model: string | null, language: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_live_transcription", { model, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Steer an active chat stream for the given session.
 */
async steerChatStream(sessionId: string, instruction: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("steer_chat_stream", { sessionId, instruction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Send a steer message to a running task.
 * 
 * This allows injecting new instructions into a running agent's ReAct loop.
 * The instruction will be processed at the next iteration of the loop.
 * 
 * Returns true if the message was sent, false if the task is not running
 * or doesn't support steering (e.g., CLI execution mode).
 */
async steerTask(taskId: string, instruction: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("steer_task", { taskId, instruction }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Stop a live transcription session gracefully.
 */
async stopLiveTranscription(transcribeId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stop_live_transcription", { transcribeId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Voice-to-text: decode base64 audio, save to temp file, call daemon transcribe tool
 */
async transcribeAudio(audioBase64: string, model: string | null, language: string | null) : Promise<Result<TranscribeResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio", { audioBase64, model, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Streaming voice-to-text: calls OpenAI API directly with stream=true,
 * emits SSE text deltas via Tauri events. Returns the transcribe_id immediately.
 */
async transcribeAudioStream(audioBase64: string, model: string | null, language: string | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("transcribe_audio_stream", { audioBase64, model, language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing agent
 */
async updateAgent(id: string, request: UpdateAgentRequest) : Promise<Result<StoredAgent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_agent", { id, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing agent task
 */
async updateBackgroundAgent(id: string, request: UpdateBackgroundAgentRequest) : Promise<Result<BackgroundAgent, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_background_agent", { id, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update a chat session.
 */
async updateChatSession(sessionId: string, updates: ChatSessionUpdateInput) : Promise<Result<ChatSession, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_chat_session", { sessionId, updates }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing secret (fails if key doesn't exist)
 */
async updateSecret(key: string, request: UpdateSecretRequest) : Promise<Result<SecretInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_secret", { key, request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Update an existing skill
 */
async updateSkill(id: string, skill: Skill) : Promise<Result<Skill, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_skill", { id, skill }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * AI model enum - Single Source of Truth for all supported models
 */
export type AIModel = "gpt-5" | "gpt-5-mini" | "gpt-5-nano" | "gpt-5-pro" | "gpt-5-1" | "gpt-5-2" | "claude-opus-4-6" | "claude-sonnet-4-5" | "claude-haiku-4-5" | "claude-code-opus" | "claude-code-sonnet" | "claude-code-haiku" | "deepseek-chat" | "deepseek-reasoner" | "gemini-2-5-pro" | "gemini-2-5-flash" | "gemini-3-pro" | "gemini-3-flash" | "groq-llama4-scout" | "groq-llama4-maverick" | "grok-4" | "grok-3-mini" | "openrouter" | "or-claude-opus-4-6" | "or-gpt-5" | "or-gemini-3-pro" | "or-deepseek-v3-2" | "or-grok-4" | "or-llama-4-maverick" | "or-qwen3-coder" | "or-devstral-2" | "or-glm-4-7" | "or-kimi-k2-5" | "or-minimax-m2-1" | "qwen3-max" | "qwen3-plus" | "glm-5" | "glm-5-code" | "glm-4-7" | "zai-coding-plan-glm-5" | "zai-coding-plan-glm-5-code" | "zai-coding-plan-glm-4-7" | "kimi-k2-5" | "doubao-pro" | "yi-lightning" | "siliconflow" | "minimax-m2-1" | "minimax-m2-5" | "minimax-coding-plan-m2-1" | "minimax-coding-plan-m2-5" | "gpt-5-codex" | "gpt-5.1-codex" | "gpt-5.2-codex" | "gpt-5.3-codex" | "opencode-cli" | "gemini-cli"
/**
 * Request to add a manual profile
 */
export type AddProfileRequest = { 
/**
 * Display name for the profile
 */
name: string; 
/**
 * API key value
 */
api_key: string; 
/**
 * Provider (anthropic, openai, google, other)
 */
provider: AuthProvider; 
/**
 * Associated email (optional)
 */
email?: string | null; 
/**
 * Priority (lower = higher priority)
 */
priority?: number }
/**
 * Agent configuration for AI-powered execution
 */
export type AgentNode = { 
/**
 * AI model to use for this agent (None = auto-select based on auth profile)
 */
model?: AIModel | null; 
/**
 * System prompt for the agent
 */
prompt?: string | null; 
/**
 * Temperature setting for model responses
 */
temperature?: number | null; 
/**
 * Optional reasoning effort override for Codex CLI models
 */
codex_cli_reasoning_effort?: string | null; 
/**
 * Optional execution mode override for Codex CLI models (`safe` | `bypass`)
 */
codex_cli_execution_mode?: CodexCliExecutionMode | null; 
/**
 * API key configuration (direct or from secret)
 */
api_key_config?: ApiKeyConfig | null; 
/**
 * List of tool names the agent is allowed to use
 */
tools?: string[] | null; 
/**
 * List of skill IDs to load into the system prompt
 */
skills?: string[] | null; 
/**
 * Variables available for skill prompt substitution
 */
skill_variables?: Partial<{ [key in string]: string }> | null; 
/**
 * Optional tier-based model routing policy.
 */
model_routing?: ModelRoutingConfig | null }
/**
 * API key or password configuration (direct value or secret reference)
 */
export type ApiKeyConfig = 
/**
 * Direct password/key value
 */
{ type: "direct"; value: string } | 
/**
 * Reference to secret name in secret manager
 */
{ type: "secret"; value: string }
/**
 * Authentication profile combining credential with metadata
 */
export type AuthProfile = { 
/**
 * Unique profile identifier
 */
id: string; 
/**
 * Display name for the profile
 */
name: string; 
/**
 * The credential data (secure references)
 */
credential: SecureCredential; 
/**
 * Where the credential was discovered from
 */
source: CredentialSource; 
/**
 * Which provider this credential is for
 */
provider: AuthProvider; 
/**
 * Current health status
 */
health?: ProfileHealth; 
/**
 * Whether this profile is enabled
 */
enabled?: boolean; 
/**
 * Priority for selection (lower = higher priority)
 */
priority?: number; 
/**
 * When the profile was created
 */
created_at: string; 
/**
 * When the profile was last used
 */
last_used_at?: string | null; 
/**
 * When the profile last failed
 */
last_failed_at?: string | null; 
/**
 * Number of consecutive failures
 */
failure_count?: number; 
/**
 * Cooldown end time if in cooldown
 */
cooldown_until?: string | null }
/**
 * Provider type for the credential
 * 
 * Distinguishes between direct API access and Claude Code CLI usage:
 * - `Anthropic`: Direct API calls using `sk-ant-api03-...` keys
 * - `ClaudeCode`: Claude Code CLI with OAuth tokens (`sk-ant-oat01-...`)
 */
export type AuthProvider = 
/**
 * Anthropic Claude API - direct API calls with API key (`sk-ant-api03-...`)
 */
"anthropic" | 
/**
 * Claude Code CLI - OAuth tokens (`sk-ant-oat01-...`)
 * 
 * Two sources of ClaudeCode tokens:
 * - `claude login`: Short-lived OAuth with refresh token (auto-discovered from ~/.claude/.credentials.json)
 * - `claude setup-token`: Long-lived OAuth token (1 year, manually added, no refresh needed)
 * 
 * Both use the same token format but differ in expiration and refresh capability.
 */
"claude_code" | 
/**
 * OpenAI API
 */
"openai" | 
/**
 * OpenAI Codex CLI
 */
"openai_codex" | 
/**
 * Google Gemini API
 */
"google" | 
/**
 * Other/Custom provider
 */
"other"
/**
 * An agent task represents a scheduled execution of an agent
 */
export type BackgroundAgent = { 
/**
 * Unique identifier for the task
 */
id: string; 
/**
 * Display name of the task
 */
name: string; 
/**
 * Description of what this task does
 */
description?: string | null; 
/**
 * ID of the agent to execute
 */
agent_id: string; 
/**
 * Chat session ID bound to this background agent
 */
chat_session_id?: string; 
/**
 * Whether the bound chat session was auto-created by background-agent storage.
 * 
 * This is used to decide safe cleanup behavior when the background agent is deleted.
 */
owns_chat_session?: boolean; 
/**
 * Input/prompt to send to the agent
 */
input?: string | null; 
/**
 * Optional template rendered to construct runtime input
 */
input_template?: string | null; 
/**
 * Schedule configuration
 */
schedule: TaskSchedule; 
/**
 * Execution mode (API or CLI)
 */
execution_mode?: ExecutionMode; 
/**
 * Optional per-task timeout (seconds) for API execution mode
 */
timeout_secs?: number | null; 
/**
 * Notification configuration
 */
notification?: NotificationConfig; 
/**
 * Memory configuration
 */
memory?: MemoryConfig; 
/**
 * Durability mode for checkpoint persistence
 */
durability_mode?: DurabilityMode; 
/**
 * Resource limits configuration
 */
resource_limits?: ResourceLimits; 
/**
 * Task IDs that must complete before this task starts.
 */
prerequisites?: string[]; 
/**
 * Continuation policy for long-horizon execution
 */
continuation?: ContinuationConfig; 
/**
 * Total iterations accumulated across all continuation segments.
 */
continuation_total_iterations?: number; 
/**
 * Number of continuation segments completed so far.
 */
continuation_segments_completed?: number; 
/**
 * Current status of the task
 */
status?: BackgroundAgentStatus; 
/**
 * Timestamp when the task was created (milliseconds since epoch)
 */
created_at: number; 
/**
 * Timestamp when the task was last updated (milliseconds since epoch)
 */
updated_at: number; 
/**
 * Timestamp of the last execution (milliseconds since epoch)
 */
last_run_at?: number | null; 
/**
 * Timestamp of the next scheduled execution (milliseconds since epoch)
 */
next_run_at?: number | null; 
/**
 * Count of successful executions
 */
success_count?: number; 
/**
 * Count of failed executions
 */
failure_count?: number; 
/**
 * Cumulative tokens used across executions
 */
total_tokens_used?: number; 
/**
 * Cumulative cost in USD across executions
 */
total_cost_usd?: number; 
/**
 * Last error message if failed
 */
last_error?: string | null; 
/**
 * Webhook configuration for external triggers
 */
webhook?: WebhookConfig | null; 
/**
 * Summary message pointer for compacted task sessions
 */
summary_message_id?: string | null }
/**
 * Status of an agent task
 */
export type BackgroundAgentStatus = 
/**
 * Task is active and will run on schedule
 */
"active" | 
/**
 * Task is paused (will not run until resumed)
 */
"paused" | 
/**
 * Task is currently running
 */
"running" | 
/**
 * Task completed (for one-time tasks)
 */
"completed" | 
/**
 * Task failed on last execution
 */
"failed" | 
/**
 * Task execution interrupted, waiting for external input to resume.
 */
"interrupted"
/**
 * Status of message execution (distinct from workflow ExecutionStatus).
 */
export type ChatExecutionStatus = 
/**
 * Execution is in progress
 */
"running" | 
/**
 * Execution completed successfully
 */
"completed" | 
/**
 * Execution failed with error
 */
"failed"
/**
 * Structured media type for a chat message.
 */
export type ChatMediaType = 
/**
 * Voice audio message.
 */
"voice"
/**
 * A single message in a chat session.
 * 
 * Represents either a user message, assistant response, or system instruction.
 * Assistant messages may include execution details showing what the agent did.
 */
export type ChatMessage = { 
/**
 * Unique identifier for this message
 */
id?: string; 
/**
 * Role of the message sender
 */
role: ChatRole; 
/**
 * Message content (text)
 */
content: string; 
/**
 * Unix timestamp in milliseconds when the message was created
 */
timestamp: number; 
/**
 * Execution details for assistant messages
 */
execution?: MessageExecution | null; 
/**
 * Optional structured media metadata.
 */
media?: ChatMessageMedia | null; 
/**
 * Optional structured transcript metadata.
 */
transcript?: ChatMessageTranscript | null }
/**
 * Structured media payload for a chat message.
 */
export type ChatMessageMedia = { 
/**
 * Media kind.
 */
media_type: ChatMediaType; 
/**
 * Local file path for this media asset.
 */
file_path: string; 
/**
 * Optional media duration in seconds.
 */
duration_sec?: number | null }
/**
 * Structured transcript payload for a chat message.
 */
export type ChatMessageTranscript = { 
/**
 * Final transcript text.
 */
text: string; 
/**
 * Optional model identifier used for transcription.
 */
model?: string | null; 
/**
 * Optional update timestamp in Unix milliseconds.
 */
updated_at?: number | null }
/**
 * Role of a message sender in a chat session.
 */
export type ChatRole = 
/**
 * Message from the user
 */
"user" | 
/**
 * Message from the AI assistant
 */
"assistant" | 
/**
 * System message (instructions, context)
 */
"system"
/**
 * A chat session containing conversation history with an agent.
 * 
 * Sessions persist conversations across application restarts and can be
 * associated with specific skills for context-aware interactions.
 * 
 * # Example
 * 
 * ```rust
 * use restflow_core::models::chat_session::{ChatSession, ChatMessage};
 * 
 * let mut session = ChatSession::new(
 * "research-agent".to_string(),
 * "claude-sonnet-4-20250514".to_string(),
 * );
 * 
 * session.add_message(ChatMessage::user("Hello!"));
 * session.add_message(ChatMessage::assistant("Hi there! How can I help?"));
 * ```
 */
export type ChatSession = { 
/**
 * Unique identifier for this session
 */
id: string; 
/**
 * Human-readable session name
 */
name: string; 
/**
 * ID of the agent this session is with
 */
agent_id: string; 
/**
 * Default model for this session
 */
model: string; 
/**
 * Ordered list of messages in the conversation
 */
messages: ChatMessage[]; 
/**
 * Unix timestamp in milliseconds when the session was created
 */
created_at: number; 
/**
 * Unix timestamp in milliseconds when the session was last updated
 */
updated_at: number; 
/**
 * Optional skill ID for context-aware sessions
 */
skill_id?: string | null; 
/**
 * Optional per-session retention policy (e.g., "1h", "1d", "7d", "30d")
 */
retention?: string | null; 
/**
 * Summary message pointer for compacted sessions
 */
summary_message_id?: string | null; 
/**
 * Cumulative prompt tokens used in this session
 */
prompt_tokens?: number; 
/**
 * Cumulative completion tokens used in this session
 */
completion_tokens?: number; 
/**
 * Total cost accumulated for this session (including compaction)
 */
cost?: number; 
/**
 * Session metadata (tokens, message count, etc.)
 */
metadata: ChatSessionMetadata; 
/**
 * Optional origin channel of this session.
 */
source_channel?: ChatSessionSource | null; 
/**
 * Optional channel-specific conversation identifier.
 */
source_conversation_id?: string | null; 
/**
 * Unix timestamp in milliseconds when the session was archived.
 * None means the session is active.
 */
archived_at?: number | null }
/**
 * Metadata for a chat session.
 * 
 * Tracks aggregate statistics about the session.
 */
export type ChatSessionMetadata = { 
/**
 * Total tokens used across all messages
 */
total_tokens: number; 
/**
 * Number of messages in the session
 */
message_count: number; 
/**
 * Last model used (may differ from session default)
 */
last_model?: string | null }
/**
 * Origin of a chat session.
 */
export type ChatSessionSource = 
/**
 * Created from workspace UI / local API entrypoints.
 */
"workspace" | 
/**
 * Created from Telegram inbound messages.
 */
"telegram" | 
/**
 * Created from Discord inbound messages.
 */
"discord" | 
/**
 * Created from Slack inbound messages.
 */
"slack" | 
/**
 * Migrated from legacy `channel:*` naming without precise channel type.
 */
"external_legacy"
/**
 * Summary view of a chat session (for listing).
 */
export type ChatSessionSummary = { 
/**
 * Session ID
 */
id: string; 
/**
 * Session name
 */
name: string; 
/**
 * Agent ID
 */
agent_id: string; 
/**
 * Model used
 */
model: string; 
/**
 * Optional skill ID for context-aware sessions
 */
skill_id?: string | null; 
/**
 * Number of messages
 */
message_count: number; 
/**
 * Last update timestamp
 */
updated_at: number; 
/**
 * Preview of last message (truncated)
 */
last_message_preview?: string | null; 
/**
 * Optional origin channel of this session.
 */
source_channel?: ChatSessionSource | null; 
/**
 * Optional channel-specific conversation identifier.
 */
source_conversation_id?: string | null; 
/**
 * Unix timestamp in milliseconds when the session was archived.
 */
archived_at?: number | null }
export type ChatSessionUpdateInput = { agentId: string | null; model: string | null; name: string | null }
/**
 * Configuration for CLI-based execution
 */
export type CliExecutionConfig = { 
/**
 * CLI binary name (e.g., "claude", "aider")
 */
binary: string; 
/**
 * Additional arguments to pass to the CLI
 */
args?: string[]; 
/**
 * Working directory for CLI execution
 */
working_dir?: string | null; 
/**
 * Timeout in seconds for CLI execution
 */
timeout_secs?: number; 
/**
 * Whether to use PTY for interactive mode
 */
use_pty?: boolean }
/**
 * Codex CLI execution mode.
 */
export type CodexCliExecutionMode = 
/**
 * Safe mode: codex runs with `--full-auto`.
 */
"safe" | 
/**
 * Bypass mode: codex runs with
 * `--dangerously-bypass-approvals-and-sandbox`.
 */
"bypass"
/**
 * Configuration for long-horizon execution continuation.
 */
export type ContinuationConfig = { 
/**
 * Automatically continue with additional segments when an execution reaches
 * the segment iteration ceiling.
 */
enabled?: boolean; 
/**
 * Maximum iterations allowed in one segment execution.
 */
segment_iterations?: number; 
/**
 * Hard cap for total iterations accumulated across all segments.
 */
max_total_iterations?: number; 
/**
 * Hard cap for cumulative LLM cost across all segments.
 */
max_total_cost_usd?: number | null; 
/**
 * Delay between segments in milliseconds to allow checkpoint persistence.
 */
inter_segment_pause_ms?: number }
/**
 * Request to convert a chat session into a background agent
 */
export type ConvertSessionToBackgroundAgentRequest = { 
/**
 * Source chat session ID
 */
session_id: string; 
/**
 * Optional name override (defaults to "Background: {session_name}")
 */
name?: string | null; 
/**
 * Optional input override (defaults to last user message)
 */
input?: string | null; 
/**
 * Whether to trigger immediate execution (default false)
 */
run_now?: boolean | null }
/**
 * Create agent request
 */
export type CreateAgentRequest = { name: string; agent: AgentNode }
/**
 * Create secret request
 */
export type CreateSecretRequest = { key: string; value: string; description: string | null }
/**
 * Source of the credential discovery
 */
export type CredentialSource = 
/**
 * Discovered from Claude Code credentials file
 */
"claude_code" | 
/**
 * Discovered from Codex CLI credentials file
 */
"codex_cli" | 
/**
 * Retrieved from macOS Keychain
 */
"keychain" | 
/**
 * Read from environment variable
 */
"environment" | 
/**
 * Manually configured by user
 */
"manual"
/**
 * Summary of discovered profiles
 */
export type DiscoverySummary = { 
/**
 * Total profiles discovered
 */
total: number; 
/**
 * Profiles by source
 */
by_source: Partial<{ [key in string]: number }>; 
/**
 * Profiles by provider
 */
by_provider: Partial<{ [key in string]: number }>; 
/**
 * Profiles that are available for use
 */
available: number; 
/**
 * Discovery errors encountered
 */
errors: string[] }
/**
 * Durability mode for checkpoint persistence.
 */
export type DurabilityMode = 
/**
 * Persist checkpoints before each tool execution.
 */
"sync" | 
/**
 * Persist checkpoints in a background task while execution continues.
 */
"async" | 
/**
 * Persist checkpoints only at execution exit.
 */
"exit"
/**
 * Execution mode for agent tasks
 */
export type ExecutionMode = 
/**
 * Use restflow-ai API executor (default)
 */
{ type: "api" } | 
/**
 * Use external CLI tool (e.g., claude, aider)
 */
({ type: "cli" } & CliExecutionConfig)
/**
 * Information about a single execution step.
 * 
 * Tracks individual steps taken during agent execution, such as
 * tool calls, API requests, or thinking processes.
 */
export type ExecutionStepInfo = { 
/**
 * Type of step (e.g., "tool_call", "api_request", "thinking")
 */
step_type: string; 
/**
 * Human-readable name of the step
 */
name: string; 
/**
 * Current status of this step
 */
status: string; 
/**
 * Duration of this step in milliseconds (if completed)
 */
duration_ms?: number | null }
/**
 * Summary of the auth profile manager state
 */
export type ManagerSummary = { total: number; enabled: number; available: number; in_cooldown: number; disabled: number; by_provider: Partial<{ [key in string]: number }>; by_source: Partial<{ [key in string]: number }> }
/**
 * A chunk of stored memory content.
 * 
 * Memory is stored in chunks for efficient retrieval and to support
 * windowed context loading. Each chunk contains a portion of a conversation
 * or document along with metadata for searching and filtering.
 * 
 * # Example
 * 
 * ```rust
 * use restflow_core::models::memory::{MemoryChunk, MemorySource};
 * 
 * let chunk = MemoryChunk::new(
 * "research-agent".to_string(),
 * "User asked about Rust async patterns...".to_string(),
 * )
 * .with_session("session-123".to_string())
 * .with_source(MemorySource::TaskExecution {
 * task_id: "task-abc".to_string(),
 * })
 * .with_tags(vec!["rust".to_string(), "async".to_string()]);
 * ```
 */
export type MemoryChunk = { 
/**
 * Unique identifier for this chunk
 */
id: string; 
/**
 * Agent ID this memory belongs to
 */
agent_id: string; 
/**
 * Optional session ID for grouping related chunks
 */
session_id?: string | null; 
/**
 * The actual memory content (text)
 */
content: string; 
/**
 * SHA-256 hash of content for deduplication
 */
content_hash: string; 
/**
 * Source of this memory
 */
source?: MemorySource; 
/**
 * Unix timestamp in milliseconds when this chunk was created
 */
created_at: number; 
/**
 * Tags for categorization and search filtering
 */
tags?: string[]; 
/**
 * Token count estimate for this chunk (for context window management)
 */
token_count?: number | null; 
/**
 * Vector embedding for semantic search
 */
embedding?: number[] | null; 
/**
 * Model used to generate the embedding (e.g., "text-embedding-3-small")
 */
embedding_model?: string | null; 
/**
 * Embedding dimension (for validation)
 */
embedding_dim?: number | null }
/**
 * Memory configuration for agent task execution
 * 
 * Controls working memory behavior and persistence settings.
 */
export type MemoryConfig = { 
/**
 * Maximum number of messages to keep in working memory
 * Older messages are discarded (no summarization)
 */
max_messages?: number; 
/**
 * Enable file memory tools (save_memory, read_memory, etc.)
 * Allows agents to persist important information to disk
 */
enable_file_memory?: boolean; 
/**
 * Persist conversation to long-term memory on task completion.
 * Working memory is chunked and stored for future retrieval.
 * Defaults to false — agents should use save_to_memory tool for selective persistence.
 */
persist_on_complete?: boolean; 
/**
 * Scope for long-term memory persistence.
 * Shared scope stores memory under the agent ID, while isolated scope
 * stores memory under a background-agent-specific namespace.
 */
memory_scope?: MemoryScope; 
/**
 * Enable working memory compaction for long-running tasks.
 */
enable_compaction?: boolean; 
/**
 * Token ratio threshold to trigger compaction against model context window.
 */
compaction_threshold_ratio?: number; 
/**
 * Upper bound for generated summary tokens during compaction.
 */
max_summary_tokens?: number }
/**
 * Response for memory list operations with pagination info.
 */
export type MemoryListResponse<T> = { 
/**
 * The items
 */
items: T[]; 
/**
 * Total count
 */
total: number }
/**
 * Scope for background-agent memory persistence.
 * 
 * Controls whether long-term memory is shared across all background agents of
 * an agent or isolated per background agent.
 */
export type MemoryScope = 
/**
 * Share long-term memory across background agents using the same agent_id.
 */
"shared_agent" | 
/**
 * Isolate long-term memory by background agent.
 */
"per_background_agent"
/**
 * A memory session representing a group of related memory chunks.
 * 
 * Sessions help organize memories by conversation or task execution.
 * Each session contains metadata and references to its chunks.
 * 
 * # Example
 * 
 * ```rust
 * use restflow_core::models::memory::MemorySession;
 * 
 * let session = MemorySession::new(
 * "research-agent".to_string(),
 * "Research on Rust async".to_string(),
 * );
 * ```
 */
export type MemorySession = { 
/**
 * Unique identifier for this session
 */
id: string; 
/**
 * Agent ID this session belongs to
 */
agent_id: string; 
/**
 * Human-readable name/title for this session
 */
name: string; 
/**
 * Optional description of the session content
 */
description?: string | null; 
/**
 * Number of chunks in this session
 */
chunk_count?: number; 
/**
 * Total token count across all chunks
 */
total_tokens?: number; 
/**
 * Unix timestamp in milliseconds when this session was created
 */
created_at: number; 
/**
 * Unix timestamp in milliseconds when this session was last updated
 */
updated_at: number; 
/**
 * Tags for the entire session
 */
tags?: string[] }
/**
 * Source of a memory chunk - where the memory originated from.
 * 
 * This helps categorize and filter memories based on their origin.
 */
export type MemorySource = 
/**
 * Memory from an agent task execution
 */
{ type: "task_execution"; task_id: string } | 
/**
 * Memory from a conversation/chat session
 */
{ type: "conversation"; session_id: string } | 
/**
 * Manually added note or annotation
 */
{ type: "manual_note" } | 
/**
 * Memory saved by agent using file memory tools
 */
{ type: "agent_generated"; tool_name: string }
/**
 * Execution details for an assistant message.
 * 
 * Contains information about what the agent did to generate the response,
 * including tool calls, duration, and token usage.
 */
export type MessageExecution = { 
/**
 * Individual steps taken during execution
 */
steps: ExecutionStepInfo[]; 
/**
 * Total execution duration in milliseconds
 */
duration_ms: number; 
/**
 * Number of tokens used for this response
 */
tokens_used: number; 
/**
 * Cost in USD for this response
 */
cost_usd?: number | null; 
/**
 * Input tokens for this response
 */
input_tokens?: number | null; 
/**
 * Output tokens for this response
 */
output_tokens?: number | null; 
/**
 * Overall execution status
 */
status: ChatExecutionStatus }
/**
 * Serializable model metadata for transferring to frontend
 */
export type ModelMetadataDTO = { model: AIModel; provider: Provider; supports_temperature: boolean; name: string }
/**
 * Model routing configuration for automatic tier-based model selection.
 */
export type ModelRoutingConfig = { 
/**
 * Enable automatic model routing.
 */
enabled: boolean; 
/**
 * Model for routine tasks (cheapest).
 */
routine_model?: string | null; 
/**
 * Model for moderate tasks.
 */
moderate_model?: string | null; 
/**
 * Model for complex tasks (most capable).
 */
complex_model?: string | null; 
/**
 * Escalate to complex tier after a failed iteration.
 */
escalate_on_failure: boolean }
/**
 * Notification configuration for task results
 */
export type NotificationConfig = { 
/**
 * Only notify on failure
 */
notify_on_failure_only?: boolean; 
/**
 * Include full output in notification
 */
include_output?: boolean; 
/**
 * Broadcast per-step tool execution updates to configured channels
 */
broadcast_steps?: boolean }
/**
 * Health status of an auth profile
 */
export type ProfileHealth = 
/**
 * Profile is healthy and available
 */
"healthy" | 
/**
 * Profile has failed recently, in cooldown
 */
"cooldown" | 
/**
 * Profile is permanently disabled
 */
"disabled" | 
/**
 * Profile status is unknown (not yet tested)
 */
"unknown"
/**
 * Response for profile operations
 */
export type ProfileResponse = { success: boolean; profile?: AuthProfile | null; error?: string | null }
/**
 * Update request for a profile
 */
export type ProfileUpdate = { name: string | null; enabled: boolean | null; priority: number | null }
/**
 * AI model provider
 */
export type Provider = "openai" | "anthropic" | "deepseek" | "google" | "groq" | "openrouter" | "xai" | "qwen" | "zai" | "zaicodingplan" | "moonshot" | "doubao" | "yi" | "siliconflow" | "minimax" | "minimaxcodingplan"
/**
 * Resource guardrails for background agent executions.
 */
export type ResourceLimits = { 
/**
 * Maximum tool calls allowed in one execution.
 */
max_tool_calls?: number; 
/**
 * Maximum execution duration in seconds.
 */
max_duration_secs?: number; 
/**
 * Maximum output payload size in bytes for tool results.
 */
max_output_bytes?: number; 
/**
 * Maximum estimated LLM cost in USD for one execution.
 */
max_cost_usd?: number | null }
/**
 * Secret info without the actual value
 */
export type SecretInfo = { key: string; description: string | null; created_at: number; updated_at: number }
/**
 * Secure credential storing secret references instead of plaintext values.
 */
export type SecureCredential = 
/**
 * API key stored in SecretStorage.
 */
{ type: "api_key"; secret_ref: string; email?: string | null } | 
/**
 * Session token stored in SecretStorage.
 */
{ type: "token"; secret_ref: string; expires_at?: string | null; email?: string | null } | 
/**
 * OAuth with references to access/refresh tokens.
 */
{ type: "o_auth"; access_token_ref: string; refresh_token_ref?: string | null; expires_at?: string | null; email?: string | null }
/**
 * A skill represents a reusable AI prompt template
 */
export type Skill = { 
/**
 * Unique identifier for the skill
 */
id: string; 
/**
 * Display name of the skill
 */
name: string; 
/**
 * Optional description of what the skill does
 */
description: string | null; 
/**
 * Optional tags for categorization
 */
tags: string[] | null; 
/**
 * Optional trigger phrases that auto-activate this skill from user input
 */
triggers: string[]; 
/**
 * The markdown content of the skill (instructions for the AI)
 */
content: string; 
/**
 * Optional folder path for skills stored on disk
 */
folder_path?: string | null; 
/**
 * Optional suggested tools for the skill
 */
suggested_tools: string[]; 
/**
 * Optional scripts defined by the skill
 */
scripts: SkillScript[]; 
/**
 * Optional references defined by the skill
 */
references: SkillReference[]; 
/**
 * Optional gating requirements for the skill
 */
gating?: SkillGating | null; 
/**
 * Optional version for the skill definition
 */
version?: string | null; 
/**
 * Optional author for the skill definition
 */
author?: string | null; 
/**
 * Optional license for the skill definition
 */
license?: string | null; 
/**
 * Optional content hash for change detection
 */
content_hash?: string | null; 
/**
 * Lifecycle status for the skill
 */
status?: SkillStatus; 
/**
 * Automatically mark skill as completed after a successful execute call
 */
auto_complete?: boolean; 
/**
 * Storage mode for the skill
 */
storage_mode?: StorageMode; 
/**
 * Whether the skill is synced between storage modes
 */
is_synced?: boolean; 
/**
 * Timestamp when the skill was created (milliseconds since epoch)
 */
created_at: number; 
/**
 * Timestamp when the skill was last updated (milliseconds since epoch)
 */
updated_at: number }
export type SkillGating = { bins?: string[] | null; env?: string[] | null; os?: string[] | null }
export type SkillReference = { id: string; path: string; title?: string | null; summary?: string | null }
export type SkillScript = { id: string; path: string; lang?: string | null }
/**
 * Skill lifecycle status used for discovery and planning.
 */
export type SkillStatus = "active" | "completed" | "archived" | "draft"
export type StorageMode = "DatabaseOnly" | "FileSystemOnly" | "Hybrid"
/**
 * Stored agent with metadata
 */
export type StoredAgent = { id: string; name: string; agent: AgentNode; prompt_file?: string | null; created_at: number | null; updated_at: number | null }
/**
 * Response for streaming task execution
 */
export type StreamingBackgroundAgentResponse = { 
/**
 * Task ID that was started
 */
task_id: string; 
/**
 * Event channel name to listen on
 */
event_channel: string; 
/**
 * Whether the task is already running (queued)
 */
already_running: boolean }
/**
 * Execution path for nested sub-agent calls. Empty for top-level tasks.
 * When Agent A spawns Agent B, Agent B's events include Agent A's subflow path
 * plus its own tool_call_id. This enables hierarchical execution tracking.
 */
export type SubflowPath = string[]
/**
 * Record of a task execution event
 */
export type TaskEvent = { 
/**
 * Unique event ID
 */
id: string; 
/**
 * Task ID this event belongs to
 */
task_id: string; 
/**
 * Event type
 */
event_type: TaskEventType; 
/**
 * Timestamp of the event (milliseconds since epoch)
 */
timestamp: number; 
/**
 * Optional message or details
 */
message?: string | null; 
/**
 * Execution output (for completion events)
 */
output?: string | null; 
/**
 * Tokens used during execution
 */
tokens_used?: number | null; 
/**
 * Cost in USD for this execution
 */
cost_usd?: number | null; 
/**
 * Duration of execution in milliseconds (for completion events)
 */
duration_ms?: number | null; 
/**
 * Subflow execution path - identifies position in nested agent call tree.
 * Empty for top-level tasks. Contains tool_call_ids when spawned by parent agent.
 */
subflow_path?: SubflowPath }
/**
 * Type of task event
 */
export type TaskEventType = 
/**
 * Task was created
 */
"created" | 
/**
 * Task started execution
 */
"started" | 
/**
 * Task completed successfully
 */
"completed" | 
/**
 * Task failed with error
 */
"failed" | 
/**
 * Task was paused
 */
"paused" | 
/**
 * Task was resumed
 */
"resumed" | 
/**
 * Notification was sent
 */
"notification_sent" | 
/**
 * Notification failed to send
 */
"notification_failed" | 
/**
 * Context compaction occurred during execution
 */
"compaction" | 
/**
 * Execution was interrupted (checkpoint created)
 */
"interrupted"
/**
 * Schedule configuration for agent tasks
 */
export type TaskSchedule = 
/**
 * Run once at a specific time
 */
{ type: "once"; run_at: number } | 
/**
 * Run on a recurring interval
 */
{ type: "interval"; interval_ms: number; start_at: number | null } | 
/**
 * Run on a cron schedule
 */
{ type: "cron"; expression: string; timezone?: string | null }
/**
 * Append-only execution event for chat turns.
 */
export type ToolTrace = { 
/**
 * Event ID.
 */
id: string; 
/**
 * Session ID this event belongs to.
 */
session_id: string; 
/**
 * Turn ID within the session.
 */
turn_id: string; 
/**
 * Optional assistant message ID (when known).
 */
message_id?: string | null; 
/**
 * Event type.
 */
event_type: ToolTraceEvent; 
/**
 * Optional tool call ID.
 */
tool_call_id?: string | null; 
/**
 * Optional tool name.
 */
tool_name?: string | null; 
/**
 * Optional tool input payload (JSON string or raw text).
 */
input?: string | null; 
/**
 * Optional tool output payload (JSON string or raw text).
 */
output?: string | null; 
/**
 * Optional file reference for full output payload.
 */
output_ref?: string | null; 
/**
 * Optional success flag (typically for tool completion).
 */
success?: boolean | null; 
/**
 * Optional duration in milliseconds.
 */
duration_ms?: number | null; 
/**
 * Optional error text.
 */
error?: string | null; 
/**
 * Event timestamp (Unix milliseconds).
 */
created_at: number }
/**
 * Event type for a persisted tool trace record.
 */
export type ToolTraceEvent = 
/**
 * A turn started execution.
 */
"turn_started" | 
/**
 * A tool call started.
 */
"tool_call_started" | 
/**
 * A tool call completed.
 */
"tool_call_completed" | 
/**
 * A turn completed successfully.
 */
"turn_completed" | 
/**
 * A turn failed.
 */
"turn_failed" | 
/**
 * A turn was cancelled.
 */
"turn_cancelled"
/**
 * Result returned by the transcribe_audio command
 */
export type TranscribeResult = { text: string; model: string }
/**
 * Update agent request
 */
export type UpdateAgentRequest = { name: string | null; agent: AgentNode | null }
/**
 * Request to update an existing agent task
 */
export type UpdateBackgroundAgentRequest = { 
/**
 * New display name (optional)
 */
name?: string | null; 
/**
 * New description (optional)
 */
description?: string | null; 
/**
 * New agent ID (optional)
 */
agent_id?: string | null; 
/**
 * New bound chat session ID (optional)
 */
chat_session_id?: string | null; 
/**
 * New input/prompt (optional)
 */
input?: string | null; 
/**
 * New runtime input template (optional)
 */
input_template?: string | null; 
/**
 * New schedule (optional)
 */
schedule?: TaskSchedule | null; 
/**
 * New notification config (optional)
 */
notification?: NotificationConfig | null; 
/**
 * New memory configuration (optional)
 */
memory?: MemoryConfig | null; 
/**
 * New per-task timeout (seconds) for API execution mode
 */
timeout_secs?: number | null; 
/**
 * New memory scope override (optional)
 */
memory_scope?: MemoryScope | null; 
/**
 * New resource limits (optional)
 */
resource_limits?: ResourceLimits | null }
/**
 * Update secret request
 */
export type UpdateSecretRequest = { value: string; description: string | null }
/**
 * Webhook configuration for a task
 */
export type WebhookConfig = { 
/**
 * Whether webhook trigger is enabled
 */
enabled?: boolean; 
/**
 * Unique webhook token for authentication
 */
token: string; 
/**
 * Optional rate limit (requests per minute)
 */
rate_limit?: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
