.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH run 1  "run " 
.SH NAME
run \- Run an agent directly
.SH SYNOPSIS
\fBrun\fR [\fB\-i\fR|\fB\-\-input\fR] [\fB\-b\fR|\fB\-\-background\fR] [\fB\-\-stream\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIAGENT_ID\fR> 
.SH DESCRIPTION
Run an agent directly
.SH OPTIONS
.TP
\fB\-i\fR, \fB\-\-input\fR \fI<INPUT>\fR
Input prompt
.TP
\fB\-b\fR, \fB\-\-background\fR
Run in background
.TP
\fB\-\-stream\fR
Stream output
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIAGENT_ID\fR>
Agent ID to run
