.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH upgrade 1  "upgrade " 
.SH NAME
upgrade \- Upgrade RestFlow CLI to the latest release
.SH SYNOPSIS
\fBupgrade\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Upgrade RestFlow CLI to the latest release
.SH OPTIONS
.TP
\fB\-\-force\fR
Reinstall even if the current version is already the latest
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
