.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH shared 1  "shared " 
.SH NAME
shared \- Shared space key\-value store
.SH SYNOPSIS
\fBshared\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Shared space key\-value store
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
shared\-list(1)
List shared space entries
.TP
shared\-get(1)
Get a shared space entry
.TP
shared\-set(1)
Set a shared space entry
.TP
shared\-delete(1)
Delete a shared space entry
.TP
shared\-help(1)
Print this message or the help of the given subcommand(s)
