.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH note 1  "note " 
.SH NAME
note \- Workspace notes management
.SH SYNOPSIS
\fBnote\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Workspace notes management
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
note\-list(1)
List workspace notes
.TP
note\-folders(1)
List distinct note folders
.TP
note\-show(1)
Show note detail
.TP
note\-create(1)
Create a note
.TP
note\-update(1)
Update a note
.TP
note\-delete(1)
Delete a note
.TP
note\-help(1)
Print this message or the help of the given subcommand(s)
