.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH session 1  "session " 
.SH NAME
session \- Manage chat sessions
.SH SYNOPSIS
\fBsession\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
Manage chat sessions
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.SH SUBCOMMANDS
.TP
session\-list(1)
List all sessions
.TP
session\-show(1)
Show a session\*(Aqs conversation
.TP
session\-create(1)
Create a new session
.TP
session\-delete(1)
Delete a session
.TP
session\-search(1)
Search across sessions
.TP
session\-help(1)
Print this message or the help of the given subcommand(s)
