"""Store API placeholders."""

from typing import Protocol, TypeVar


T = TypeVar("T")


class Store(Protocol[T]):
    def get(self, id: str) -> T | None: ...
    def list(self) -> list[T]: ...
    def put(self, id: str, value: T) -> None: ...
    def delete(self, id: str) -> bool: ...
    def exists(self, id: str) -> bool: ...
