name: Claude Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  issues: write
  contents: read

jobs:
  code-review:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Claude Code Assistant
        uses: anthropics/claude-code-action@v1
        with:
          # Automatically review PR changes
          prompt: |
            Review this Pull Request code changes, focusing on:
            1. Code quality and maintainability
            2. Potential bugs and logical errors
            3. Performance issues
            4. Adherence to project coding standards
            5. Test coverage

            Please provide detailed review comments.

        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
